"""add whatsapp column to users

Revision ID: dabe78eac40b
Revises: 96e87d719cfe
Create Date: 2025-11-25 08:56:10.951229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dabe78eac40b'
down_revision: Union[str, Sequence[str], None] = '96e87d719cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('whatsapp', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_whatsapp'), 'users', ['whatsapp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_whatsapp'), table_name='users')
    op.drop_column('users', 'whatsapp')
    # ### end Alembic commands ###
